# Generated by Django 3.2.6 on 2021-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='valor',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
