# Generated by Django 3.2.6 on 2021-08-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_preguntas', '0002_respuesta_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Consigna',
            new_name='consigna',
        ),
    ]
