# Generated by Django 3.2.6 on 2021-08-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_preguntas', '0003_rename_consigna_pregunta_consigna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='correcto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responde_a', to='app_preguntas.respuesta'),
        ),
    ]
