# Generated by Django 3.2.6 on 2021-08-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_preguntas', '0004_alter_pregunta_correcto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_preguntas.categoria')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JuegoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('in_progress', 'En Progreso'), ('correct', 'Correcto'), ('incorrect', 'Incorrecto'), ('ended', 'Finalizado')], default='in_progress', max_length=15)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_respuestas', to='app_juego.juego')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalle_respuestas', to='app_preguntas.pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_preguntas.respuesta')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='preguntas',
            field=models.ManyToManyField(through='app_juego.JuegoPregunta', to='app_preguntas.Pregunta'),
        ),
    ]
