# Generated by Django 3.2.6 on 2021-08-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_preguntas', '0004_alter_pregunta_correcto'),
        ('app_juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegopregunta',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_preguntas.respuesta'),
        ),
    ]
