# Generated by Django 3.2.6 on 2021-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juego', '0002_alter_juegopregunta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegopregunta',
            name='estado',
            field=models.CharField(choices=[('in_progress', 'En Progreso'), ('correct', 'Correcto'), ('incorrect', 'Incorrecto'), ('ended', 'Finalizado')], default='in_progress', max_length=30),
        ),
    ]
